apiVersion: v1
kind: ConfigMap
metadata:
  name: leaderboard-config
data:
  GCP_PROJECT_ID: "<your-gcp-project-id>"
  GCS_BUCKET_NAME: "ldb_bucket"
  KAFKA_TOPIC: "leaderboard_events"
  KAFKA_BROKERS: "bootstrap.leaderboard-kafka-cluster-main.us-central1.managedkafka.aftermath-69.cloud.goog:9092"
  REDIS_HOST: "10.194.0.3"
  REDIS_PORT: "6379"