apiVersion: v1
kind: ConfigMap
metadata:
  name: leaderboard-config
data:
  GCP_PROJECT_ID: "aftermath-69"
  GCS_BUCKET_NAME: "ldb-us-central1-bucket-v2"
  PUBSUB_TOPIC_ID: "leaderboard_events"
  PUBSUB_SUBSCRIPTION_ID_BATCH: "leaderboard-batch-sub"
  PUBSUB_SUBSCRIPTION_ID_REALTIME: "leaderboard-realtime-sub"
  REDIS_HOST: "10.144.0.3"
  REDIS_PORT: "6378"
 # Placeholder for dynamic image tagging

 